---
# packages_present:
#   - bsd-mailx
#   - dnsutils
#   - iproute2
#   - iputils-ping

# packages_absent:
#   - systemd-timesyncd

# apt_packages:
#   - name: dmidecode
#     default_release: bookworm-backports

apt_packages: []
