---
- name: Restart pushprox-client
  ansible.builtin.systemd_service:
    name: pushprox-client.service
    enabled: true
    state: restarted
    daemon_reload: true

- name: Restart pushprox-proxy
  ansible.builtin.systemd_service:
    name: pushprox-proxy.service
    enabled: true
    state: restarted
    daemon_reload: true
