---
# Default filename for traditional one-line format found in /etc/apt/sources.list
apt_repositories_default_filename: /etc/apt/sources

# Default location for storing GPG keyrings
apt_repositories_default_keyrings_dest: /etc/apt/keyrings/

# Key urls to download
# apt_repositories_key_urls:
#   - url: http://some_key_url
#
#   - url: http://some_other_key_url
#     dest: /some/specific/filename.key
apt_repositories_key_urls: []

# Traditional one-line format repositories
# - filename: sets the name of the source list file in sources.list.d.
#   The .list extension will be automatically added.
# apt_repositories:
#   - repo: 'deb http://mirror.example.com/debian bookworm main contrib non-free non-free-firmware'
#
#   - repo: 'deb [check-valid-until=no] http://mirror.example.com/debian bookworm-updates main contrib non-free non-free-firmware'
#     filename: updates
#
#   - repo: 'deb [signed-by=/etc/apt/keyrings/mirror.key] http://mirror.example.com/debian-security bookworm-security main contrib non-free'
#     state: 'present'
#     filename: security
#
#   - repo: 'deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware'
#     state: 'absent'
apt_repositories: []

# Repositories in deb822 format
# deb822_repositories:
#   - name: ubuntu
#     types: [deb]
#     uris: http://archive.ubuntu.com/ubuntu/
#     suites: [noble, noble-updates, noble-backports]
#     components: [main, restricted, universe, multiverse]
#     signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
deb822_repositories: []
