---
# Default filename for traditional "One-Line-Style Format"
# The .list extension will be automatically added.
apt_repositories_default_filename: /etc/apt/sources

# Default location for storing GPG keyrings
apt_repositories_default_keyrings: /etc/apt/keyrings/

# Key urls to download
apt_repositories_key_urls: []

# apt_repositories_key_urls:
#   - url: http://some_key_url
#   - url: http://some_other_key_url
#     dest: /some/specific/filename.key

# "One-Line-Style Format" repositories, using .list file extension.
apt_repositories_list: []

# apt_repositories_list:
#   - repo: 'deb http://mirror.example.com/debian bookworm main contrib non-free non-free-firmware'
#
#   - repo: 'deb [check-valid-until=no] http://mirror.example.com/debian bookworm-updates main contrib non-free non-free-firmware'
#     filename: updates
#
#   - repo: 'deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware'
#     state: 'absent'

# "Deb822-style Format" repositories, using .sources file extension.
apt_repositories_sources: []

# apt_repositories_sources:
#   - name: ubuntu
#     types: [deb]
#     uris: http://archive.ubuntu.com/ubuntu/
#     suites: [noble, noble-updates, noble-backports]
#     components: [main, restricted, universe, multiverse]
#     signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

# APT Update cache ?
apt_repositories_cache_valid_time: 0
apt_repositories_update_cache: false
