---
# Default filename for traditional one-line format found in /etc/apt/sources.list
apt_repositories_default_filename: /etc/apt/sources

# Key urls to download to /etc/apt/keyrings/
# apt_repositories_key_urls:
#   - url: http://some_key_url
#     dest: /etc/apt/keyrings/some.key
apt_repositories_key_urls: []

# Traditional one-line format repositories
# apt_repositories:
#   - repo: 'deb http://mirror.example.com/debian bookworm main contrib non-free non-free-firmware'
#
#   - repo: 'deb [check-valid-until=no] http://mirror.example.com/debian bookworm-updates main contrib non-free non-free-firmware'
#     filename: updates
#
#   - repo: 'deb http://mirror.example.com/debian-security bookworm-security main contrib non-free non-free-firmware'
#     state: 'present'
#     filename: security
#
#   - repo: 'deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware'
#     state: 'absent'
apt_repositories: []

# Repositories in deb822 format
# apt_repositories_deb822:
#   - name: ubuntu
#     types: [deb]
#     uris: http://archive.ubuntu.com/ubuntu/
#     suites: [noble, noble-updates, noble-backports]
#     components: [main, restricted, universe, multiverse]
#     signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
apt_repositories_deb822: []
